### ISSUE TITLE
app crash on android 4.3

### ISSUE THREAD

**Issue by chnbohwr** [MOPCON/App-Android#180]
![image](https://user-images.githubusercontent.com/6761222/59364154-f3ecac00-8d68-11e9-8ac5-6ea595bdfb50.png)

### 錯誤1
```
FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/org.mopcon.session.app-1.apk
	at android.app.ActivityThread.installProvider(ActivityThread.java:5122)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: /data/app/org.mopcon.session.app-1.apk
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5107)
	... 12 more
```

### 錯誤2
```
FATAL EXCEPTION: Background tasks
android.database.sqlite.SQLiteException: no such table: server_preferences (code 1): , while compiling: SELECT * FROM server_preferences WHERE (name = ?)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1118)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:691)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1436)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
	at com.google.android.gm.provider.MailEngine.getServerPrefsCursor(MailEngine.java:1462)
	at com.google.android.gm.provider.MailEngine.getCursorForReplyFromDefaultAddress(MailEngine.java:1466)
	at com.google.android.gm.provider.MailEngine.notifyInitializationComplete(MailEngine.java:1371)
	at com.google.android.gm.provider.MailEngine.access$1900(MailEngine.java:135)
	at com.google.android.gm.provider.MailEngine$5.run(MailEngine.java:1291)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by chnbohwr** [comment]
20221 版的時候快掃沒有發現這個問題
先關閉再觀察，如果再有問題我再 reopen

![image](https://user-images.githubusercontent.com/6761222/61712108-29cd7900-ad88-11e9-9550-d1ef1424a44e.png)

**Comment by RaphaHsu** [comment]
Due to multidex setup, fixed

ref:
https://rnfirebase.io/#android-enabling-multidex
